# BackgroundDisplay.gd
# Generated by Lupine Engine - Background Display UI Script
# Manages the background display UI for the Background Manager

extends Control

# Background references
@onready var background_rect = $Background
@onready var key_image_rect = $KeyImage

func _ready():
	# Register this display with the Background Manager
	if BackgroundManager:
		BackgroundManager.register_background_display(self)
		BackgroundManager.register_key_image_display(key_image_rect)
	
	print("Background Display UI initialized")

# Optional: Handle background transition effects
func fade_to_background(texture: Texture2D, duration: float = 0.5):
	if not background_rect:
		return
	
	var tween = create_tween()
	tween.tween_property(background_rect, "modulate:a", 0.0, duration / 2)
	tween.tween_callback(func(): background_rect.texture = texture)
	tween.tween_property(background_rect, "modulate:a", 1.0, duration / 2)

func slide_to_background(texture: Texture2D, direction: Vector2, duration: float = 0.5):
	if not background_rect:
		return
	
	var original_pos = background_rect.position
	var slide_distance = background_rect.size * direction
	
	# Set new texture and position it off-screen
	background_rect.texture = texture
	background_rect.position = original_pos + slide_distance
	
	# Slide into position
	var tween = create_tween()
	tween.tween_property(background_rect, "position", original_pos, duration)
